"""
Viz tools – Plotly chart generators.

These charts help visualize pipeline health, record quality trends,
and duration anomalies. All figures are stored in st.session_state.charts
for the app to pick up and render.
"""

import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
import pandas as pd
import numpy as np
from langchain_core.tools import tool
from data.loader import get_roster_data, get_market_data
from data.query_engine import (
    enrich_roster, aggregate_roster, cross_table_join,
    retry_effectiveness, get_stuck_ros, compute_record_quality,
)

# Fallback in-process buffer for charts generated inside tool execution.
# This is used when Streamlit session state is not writable from the tool context.
_CHART_BUFFER = []


def clear_generated_charts() -> None:
    """Clear any buffered charts from previous runs."""
    _CHART_BUFFER.clear()


def consume_generated_charts() -> list:
    """Return and clear buffered charts generated by viz tools."""
    charts = list(_CHART_BUFFER)
    _CHART_BUFFER.clear()
    return charts

def _store_chart(fig, title):
    """Save a Plotly figure to session state."""
    fig.update_layout(
        template="plotly_dark",
        paper_bgcolor="rgba(15,15,26,0.8)",
        plot_bgcolor="rgba(15,15,26,0.6)",
        font=dict(family="Inter, sans-serif", color="#e0e0e0"),
        title=dict(font=dict(size=18, color="#6dd5ed")),
        margin=dict(l=40, r=40, t=60, b=40),
        legend=dict(bgcolor="rgba(0,0,0,0.3)", bordercolor="rgba(255,255,255,0.1)"),
    )
    chart_payload = {"fig": fig, "title": title}

    # Always keep a process-local copy so the app can recover charts even
    # when session_state is unavailable in tool execution context.
    _CHART_BUFFER.append(chart_payload)

    # Best-effort write into Streamlit session state for backward compatibility.
    try:
        if "charts" not in st.session_state:
            st.session_state.charts = []
        st.session_state.charts.append(chart_payload)
    except Exception:
        pass

    return f"📊 Chart generated: **{title}**. It will appear below this message."

@tool
def chart_pipeline_health_heatmap(state: str = "") -> str:
    """Heatmap showing % Red flags across pipeline stages per state.
    
    Instantly spots bottlenecks: which states have trouble at which stage?
    """
    df = get_roster_data()
    if state:
        df = df[df["CNT_STATE"].str.upper() == state.upper()]
    
    health_cols = {
        "PRE_PROCESSING_HEALTH": "Pre-Processing",
        "MAPPING_APROVAL_HEALTH": "Mapping Approval",
        "ISF_GEN_HEALTH": "ISF Generation",
        "DART_GEN_HEALTH": "DART Generation",
        "DART_REVIEW_HEALTH": "DART Review",
        "DART_UI_VALIDATION_HEALTH": "DART UI Validation",
        "SPS_LOAD_HEALTH": "SPS Load",
    }
    
    existing = {k: v for k, v in health_cols.items() if k in df.columns}
    if not existing:
        return "No health flag data found."
    
    records = []
    for col, label in existing.items():
        by_state = df.groupby("CNT_STATE")[col].apply(
            lambda x: (x.str.strip().str.lower() == "red").sum() / max(len(x), 1) * 100
        ).reset_index()
        by_state.columns = ["State", "Red_Pct"]
        by_state["Stage"] = label
        records.append(by_state)
    
    heatmap_df = pd.concat(records)
    pivot = heatmap_df.pivot(index="State", columns="Stage", values="Red_Pct").fillna(0)
    col_order = [v for v in health_cols.values() if v in pivot.columns]
    pivot = pivot[col_order]
    
    fig = px.imshow(
        pivot.values,
        labels=dict(x="Pipeline Stage", y="State", color="% Red Flags"),
        x=col_order,
        y=pivot.index.tolist(),
        color_continuous_scale=["#1a1a2e", "#ffc107", "#f44336"],
        aspect="auto",
        title="Pipeline Stage Health Heatmap — % Red Flags by State",
    )
    fig.update_xaxes(side="top")
    return _store_chart(fig, "Pipeline Stage Health Heatmap")

@tool
def chart_record_quality_breakdown(state: str = "", top_n: int = 15) -> str:
    """Bar chart showing average HEALTH_SCORE per organization.
    
    Args:
        state: Optional state filter.
        top_n: Number of orgs to show (default 15, worst first).
    """
    df = enrich_roster(get_roster_data())
    if state:
        df = df[df["CNT_STATE"].str.upper() == state.upper()]
    if df.empty:
        return "No data found."
    
    org_health = df.groupby("ORG_NM").agg(
        avg_health=("HEALTH_SCORE", "mean"),
        count=("RO_ID", "count"),
    ).reset_index()
    
    org_health = org_health.nsmallest(top_n, "avg_health")
    org_health["Org"] = org_health["ORG_NM"].str[:30]
    
    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=org_health["Org"],
        y=org_health["avg_health"],
        marker_color=org_health["avg_health"].apply(
            lambda x: "#f44336" if x < 50 else "#ffc107" if x < 75 else "#00c853"
        ),
    ))
    fig.update_layout(
        title=f"Worst {top_n} Orgs by Health Score" + (f" ({state})" if state else ""),
        xaxis_title="Organization", yaxis_title="Health Score (0-100)",
        xaxis_tickangle=-45,
    )
    return _store_chart(fig, "Record Quality Breakdown")

@tool
def chart_duration_anomalies(stage: str = "DART_GEN_DURATION") -> str:
    """Box plot showing duration distribution per state.
    
    Helps spot outliers in specific stages.
    """
    df = get_roster_data()
    if stage not in df.columns:
        return f"Column '{stage}' missing."
    
    plot_df = df[["CNT_STATE", stage]].dropna()
    title = stage.replace("_DURATION", "").replace("_", " ").title()
    
    fig = px.box(
        plot_df, x="CNT_STATE", y=stage, color="CNT_STATE",
        title=f"Duration Distribution — {title}",
        labels={"CNT_STATE": "State", stage: "Minutes"},
    )
    fig.update_layout(showlegend=False, xaxis_tickangle=-45)
    return _store_chart(fig, f"{title} Duration Anomalies")

@tool
def chart_market_scs_trend() -> str:
    """Line chart showing market success trends over time."""
    df = get_market_data()
    if "MONTH" not in df.columns:
        return "Missing MONTH column."
    
    df = df.copy()
    df["MONTH_DT"] = pd.to_datetime(df["MONTH"], format="%m-%Y")
    df = df.sort_values("MONTH_DT")
    
    fig = px.line(
        df, x="MONTH", y="SCS_PERCENT", color="MARKET",
        title="Market Success Rate Trends",
        markers=True,
    )
    fig.add_hline(y=95, line_dash="dash", line_color="#f44336", annotation_text="95% Target")
    return _store_chart(fig, "Market SCS% Trend")

@tool
def chart_retry_lift(state: str = "") -> str:
    """Grouped bar chart: First-pass vs Post-retry success rates."""
    df = retry_effectiveness(state=state or None)
    if df.empty:
        return "No retry data."
    
    plot_df = df.head(15).copy()
    plot_df["Label"] = plot_df["MARKET"] + " (" + plot_df["MONTH"] + ")"
    
    fig = go.Figure()
    fig.add_trace(go.Bar(name="First Pass", x=plot_df["Label"], y=plot_df["FIRST_ITER_SCS_RATE"], marker_color="#3a7bd5"))
    fig.add_trace(go.Bar(name="Post Retry", x=plot_df["Label"], y=plot_df["POST_RETRY_SCS_RATE"], marker_color="#00c853"))
    
    fig.update_layout(
        barmode="group",
        title="Retry Lift — First Pass vs Final" + (f" ({state})" if state else ""),
        xaxis_tickangle=-45,
    )
    return _store_chart(fig, "Retry Lift Analysis")

@tool
def chart_stuck_ro_tracker() -> str:
    """Dashboard view of currently stuck ROs."""
    df = get_stuck_ros()
    if df.empty:
        return "✅ No stuck ROs!"
    
    fig = go.Figure()
    for i, (_, row) in enumerate(df.iterrows()):
        org, state, count = row.get("ORG_NM", "??")[:20], row.get("CNT_STATE", "?"), int(row.get("RED_FLAG_COUNT", 0))
        color = "#f44336" if count >= 3 else "#ffc107" if count >= 1 else "#4caf50"
        fig.add_trace(go.Indicator(
            mode="number+delta", value=count,
            title={"text": f"{org} ({state})"},
            number={"prefix": "🔴 ", "font": {"color": color}},
            domain={"row": i // 3, "column": i % 3}
        ))
    
    rows = (len(df) + 2) // 3
    fig.update_layout(grid={"rows": rows, "columns": 3, "pattern": "independent"}, height=200 * rows)
    return _store_chart(fig, "Stuck RO Tracker")

ALL_VIZ_TOOLS = [
    chart_pipeline_health_heatmap,
    chart_record_quality_breakdown,
    chart_duration_anomalies,
    chart_market_scs_trend,
    chart_retry_lift,
    chart_stuck_ro_tracker,
]
